### ISSUE TITLE
Passing doubles to methods doesn't seem to work

### ISSUE THREAD

**Issue by blicksyne** [GodotNativeTools/godot-cpp#49] opened 2017-10-24 12:14 UTC
When trying to call functions that take doubles as arguments (double on the bindings side usually and float internally), the value received by the function in the bindings is correct, but the value received inside the actual function is incorrect. Some examples are: set_rotation_deg, set_rotation, set_rotation_in_degrees. The value received on the engine side is NaN for most functions affected by this. Another affected function is set_anchor. In this case a 0 is received when 1 is passed as the second argument.

My local godot, godot-cpp and godot_headers repositories are up-to-date and I'm on Ubuntu 17.06 using GCC. The issue was also present on Windows 10 using MSVC, before the linking issue on Windows appeared.

**Comment by karroffel** [comment] 2018-01-12 07:52
Ah yes, that is because there is no ArgCast for doubles.

I'll add it soon

**Comment by karroffel** [comment] 2018-01-19 11:04
The problem is that doubles aren't supported in Variant, so it's not useful to use them whenever you interface with Godot. Not much we can do about it here in the bindings :(

**Comment by qpeq** [comment] 2018-02-06 15:36
Found this issue recently.That's...very sad.
The issue makes it impossible to write games with GDNative/C++.
How is it possible that it doesn't happen on another language binding such as C# or rust?

**Comment by karroffel** [comment] 2018-02-07 14:01
Oh, turns out that there is a problem here actually. I'll look into this today.

**Comment by karroffel** [comment] 2018-03-30 21:22
Actually the problem aren't the doubles, the problem are floats. Godot ptrcall expects all floating point numbers to be passed via `double *`, even in the case of floats.

This is fixed on the nativescript-1.1 branch, by the commit 2dbc73f.

If there's much demand then this is easy to cherry pick, but I hope to get the nativescript-1.1 branch into a stable state very soon anyway.

**Comment by BastiaanOlij** [comment] 2018-11-22 11:36
Seeing nativescript 1.1 has now been merged into master I'm closing this.

**Closed by BastiaanOlij** 2018-11-22 11:36 UTC
