### ISSUE TITLE
use mingw g++ take error~~

### ISSUE THREAD

**Issue by Phin236** [GodotNativeTools/godot-cpp#345] opened 2019-11-09 08:49 UTC
![GB@IJ8KB4F5}U7F)AXKNAZR](https://user-images.githubusercontent.com/34740477/68525842-d53b1300-0310-11ea-9746-de710c01cd29.png)

**Comment by Zylann** [comment] 2020-03-31 19:32
Duplicate of https://github.com/GodotNativeTools/godot-cpp/issues/376

**Closed** 2020-04-01 23:07 UTC
