### ISSUE TITLE
Compiling bindings from the master branch errors on Linux

### ISSUE THREAD

**Issue by Gramps** [GodotNativeTools/godot-cpp#268] opened 2019-04-13 18:20 UTC
As the title says, when I attempt to compile the bindings from the master branch, I get the following errors.  I am using Ubuntu Linux 18.04 LTS.

```
scons plaform=linux generate_bindings=yes bits=64
scons: Reading SConscript files ...
scons: done reading SConscript files.
scons: Building targets ...
g++ -o src/core/Plane.o -c -fPIC -g -std=c++14 -Wwrite-strings -Og -m64 -I. -Igodot_headers -Iinclude -Iinclude/gen -Iinclude/core src/core/Plane.cpp
g++ -o src/core/RID.o -c -fPIC -g -std=c++14 -Wwrite-strings -Og -m64 -I. -Igodot_headers -Iinclude -Iinclude/gen -Iinclude/core src/core/RID.cpp
g++ -o src/core/NodePath.o -c -fPIC -g -std=c++14 -Wwrite-strings -Og -m64 -I. -Igodot_headers -Iinclude -Iinclude/gen -Iinclude/core src/core/NodePath.cpp
g++ -o src/core/Variant.o -c -fPIC -g -std=c++14 -Wwrite-strings -Og -m64 -I. -Igodot_headers -Iinclude -Iinclude/gen -Iinclude/core src/core/Variant.cpp
In file included from include/core/Variant.hpp:9:0,
                 from src/core/Variant.cpp:1:
include/core/Basis.hpp:25:13: error: declaration of template parameter 'column' shadows template parameter
   template <int column, int component>
             ^~~
include/core/Basis.hpp:22:12: note: template parameter 'column' declared here
  template <int column>
            ^~~
include/core/Basis.hpp: In member function 'godot::Basis::ColumnVector3<column>::ColumnVectorComponent<column, component>& godot::Basis::ColumnVector3<column>::ColumnVectorComponent<column, component>::operator=(const real_t&)':
include/core/Basis.hpp:40:5: error: 'element' was not declared in this scope
     element[component][column] = p_value;
     ^~~~~~~
include/core/Basis.hpp:40:5: note: suggested alternative: 'elements'
     element[component][column] = p_value;
     ^~~~~~~
     elements
include/core/Basis.hpp: In member function 'godot::Basis::ColumnVector3<column>::ColumnVectorComponent<column, component>::operator real_t() const':
include/core/Basis.hpp:45:12: error: 'element' was not declared in this scope
     return element[component][column];
            ^~~~~~~
include/core/Basis.hpp:45:12: note: suggested alternative: 'elements'
     return element[component][column];
            ^~~~~~~
            elements
include/core/Basis.hpp: In member function 'godot::Basis::ColumnVector3<column>::operator godot::String() const':
include/core/Basis.hpp:275:3: error: expected ';' before '}' token
   }
   ^
include/core/Basis.hpp: In member function 'const godot::Vector3& godot::Basis::operator[](int) const':
include/core/Basis.hpp:311:23: warning: returning reference to temporary [-Wreturn-local-addr]
   return get_axis(axis);
                       ^
scons: *** [src/core/Variant.o] Error 1

```

**Comment by omar-bz** [comment] 2019-04-14 09:06
+1, I have the exact same error, meanwhile the build on the "godot-cpp" submodule in the cpp example given in godot official tutorial on gdnative compile successfully(https://github.com/BastiaanOlij/gdnative_cpp_example) it is pointing on bcc39bbf4bf9922c1a5eaea91885eda05cd1202c at the time I am writing this.

**Comment by BastiaanOlij** [comment] 2019-04-14 10:24
Might want to stick with the 3.1 branch for now, we merged a few things into master the other day that may be the cause of this.

@aqnuep can you have a look into this? Maybe check out the fix windfish offered a PR for?

**Comment by omar-bz** [comment] 2019-04-14 10:28
there is another error on the 3.1 branch as I mentioned I am using "Debian GNU/Linux 9 (stretch)" by the way i forgot to mention that : 

`scons: Reading SConscript files ...
scons: done reading SConscript files.
scons: Building targets ...
g++ -o src/core/Rect2.o -c -fPIC -g -std=c++14 -Wwrite-strings -Og -m32 -I. -Igodot_headers -Iinclude -Iinclude/gen -Iinclude/core src/core/Rect2.cpp
In file included from /usr/include/stdint.h:25:0,
                 from /usr/lib/gcc/x86_64-linux-gnu/6/include/stdint.h:9,
                 from godot_headers/gdnative/vector2.h:38,
                 from include/core/Vector2.hpp:4,
                 from include/core/Rect2.hpp:4,
                 from src/core/Rect2.cpp:1:
/usr/include/features.h:364:25: fatal error: sys/cdefs.h: No such file or directory
 #  include <sys/cdefs.h>
                         ^
compilation terminated.
g++ -o src/core/Variant.o -c -fPIC -g -std=c++14 -Wwrite-strings -Og -m32 -I. -Igodot_headers -Iinclude -Iinclude/gen -Iinclude/core src/core/Variant.cpp
g++ -o src/core/Vector2.o -c -fPIC -g -std=c++14 -Wwrite-strings -Og -m32 -I. -Igodot_headers -Iinclude -Iinclude/gen -Iinclude/core src/core/Vector2.cpp
In file included from /usr/include/stdint.h:25:0,
                 from /usr/lib/gcc/x86_64-linux-gnu/6/include/stdint.h:9,
                 from godot_headers/gdnative/variant.h:38,
                 from include/core/Variant.hpp:4,
                 from src/core/Variant.cpp:1:
/usr/include/features.h:364:25: fatal error: sys/cdefs.h: No such file or directory
 #  include <sys/cdefs.h>
                         ^
compilation terminated.
g++ -o src/core/Array.o -c -fPIC -g -std=c++14 -Wwrite-strings -Og -m32 -I. -Igodot_headers -Iinclude -Iinclude/gen -Iinclude/core src/core/Array.cpp
In file included from /usr/include/stdint.h:25:0,
                 from /usr/lib/gcc/x86_64-linux-gnu/6/include/stdint.h:9,
                 from godot_headers/gdnative/vector2.h:38,
                 from include/core/Vector2.hpp:4,
                 from src/core/Vector2.cpp:1:
/usr/include/features.h:364:25: fatal error: sys/cdefs.h: No such file or directory
 #  include <sys/cdefs.h>
                         ^
compilation terminated.
g++ -o src/core/Transform2D.o -c -fPIC -g -std=c++14 -Wwrite-strings -Og -m32 -I. -Igodot_headers -Iinclude -Iinclude/gen -Iinclude/core src/core/Transform2D.cpp
In file included from /usr/include/stdint.h:25:0,
                 from /usr/lib/gcc/x86_64-linux-gnu/6/include/stdint.h:9,
                 from godot_headers/gdnative/array.h:38,
                 from include/core/Array.hpp:4,
                 from src/core/Array.cpp:1:
/usr/include/features.h:364:25: fatal error: sys/cdefs.h: No such file or directory
 #  include <sys/cdefs.h>
                         ^
compilation terminated.
g++ -o src/core/PoolArrays.o -c -fPIC -g -std=c++14 -Wwrite-strings -Og -m32 -I. -Igodot_headers -Iinclude -Iinclude/gen -Iinclude/core src/core/PoolArrays.cpp
In file included from /usr/include/stdint.h:25:0,
                 from /usr/lib/gcc/x86_64-linux-gnu/6/include/stdint.h:9,
                 from godot_headers/gdnative/vector2.h:38,
                 from include/core/Vector2.hpp:4,
                 from include/core/Transform2D.hpp:4,
                 from src/core/Transform2D.cpp:1:
/usr/include/features.h:364:25: fatal error: sys/cdefs.h: No such file or directory
 #  include <sys/cdefs.h>
                         ^
compilation terminated.
g++ -o src/core/Quat.o -c -fPIC -g -std=c++14 -Wwrite-strings -Og -m32 -I. -Igodot_headers -Iinclude -Iinclude/gen -Iinclude/core src/core/Quat.cpp
In file included from /usr/include/stdio.h:27:0,
                 from include/core/Defs.hpp:98,
                 from include/core/PoolArrays.hpp:4,
                 from src/core/PoolArrays.cpp:1:
/usr/include/features.h:364:25: fatal error: sys/cdefs.h: No such file or directory
 #  include <sys/cdefs.h>
                         ^
compilation terminated.
scons: *** [src/core/Rect2.o] Error 1
g++ -o src/core/TagDB.o -c -fPIC -g -std=c++14 -Wwrite-strings -Og -m32 -I. -Igodot_headers -Iinclude -Iinclude/gen -Iinclude/core src/core/TagDB.cpp
scons: *** [src/core/Variant.o] Error 1
scons: *** [src/core/Vector2.o] Error 1
scons: *** [src/core/Array.o] Error 1
scons: *** [src/core/Transform2D.o] Error 1
scons: *** [src/core/PoolArrays.o] Error 1
In file included from include/core/Quat.hpp:4:0,
                 from src/core/Quat.cpp:1:
/usr/include/c++/6/cmath:41:28: fatal error: bits/c++config.h: No such file or directory
 #include <bits/c++config.h>
                            ^
compilation terminated.
scons: *** [src/core/Quat.o] Error 1
In file included from /usr/include/c++/6/unordered_map:38:0,
                 from src/core/TagDB.cpp:3:
/usr/include/c++/6/utility:68:28: fatal error: bits/c++config.h: No such file or directory
 #include <bits/c++config.h>
                            ^
compilation terminated.
scons: *** [src/core/TagDB.o] Error 1
scons: building terminated because of errors.`

**Comment by aqnuep** [comment] 2019-04-14 10:35
> Might want to stick with the 3.1 branch for now, we merged a few things into master the other day that may be the cause of this.
> 
> @aqnuep can you have a look into this? Maybe check out the fix windfish offered a PR for?

PR https://github.com/GodotNativeTools/godot-cpp/pull/264 and https://github.com/GodotNativeTools/godot-cpp/pull/266 should fix the errors related to the Basis class changes in the OP.

**Comment by BastiaanOlij** [comment] 2019-04-14 11:26
Ok, I merged both in, @karroffel had already approved them. Riot was hacked the other day so the IRC bridge is down, so it's a bit hard keeping in touch :)

**Comment by Gramps** [comment] 2019-04-14 21:50
Yeah, I had an issue with the 3.1 branch, like @omar-bz, then just kind of gave up for weekend.  Good to hear that there were some fixes merged in!  I'll give it a go next weekend.

Shit, what rotten bastards hacked Riot?

**Comment by mudlee** [comment] 2019-04-20 17:47
I can confirm, that now it works, at least on OSX. I had the same error before.

**Comment by Gramps** [comment] 2019-04-20 18:14
I can now confirm that compiling bindings on the **current** master branch works.

That being said, I get issues when trying to compile my plug-in beyond that which seems to be a combination of things.  It appears some changes in the master branch means I have to re-write portions of my plugin.

I presume sticking with the 3.1 branch is the way to go as too many undocumented (for now) changes seem to have occurred in the master branch.

@mudlee   I think it gives it a **debug** name unless you use target=release.  It'll be named something like godot-cpp.osx.debug.64 or such.  I have the same thing happen in Linux.  I had to re-write the SConstruct file for my plugin because of it.  There are also more changes I now have to fix.

**Comment by mudlee** [comment] 2019-04-20 18:16
I was just about to edit my edit (lol), it was my bad, I ran it under my test directory in a wrong terminal tab. Apologies. So yes, it works here too.

**Closed** 2019-04-20 18:16 UTC
