### ISSUE TITLE
Only the first library loaded has access to _type_tag and cast_to<T> function

### ISSUE THREAD

**Issue by yosagi** [GodotNativeTools/godot-cpp#394] opened 2020-04-14 08:32 UTC
## Problem
I have multiple GDNative c++ classes in multiple so/dll libraries. Among all libraries, only the first library can use cast_to<T>() properly. On the library other than the first one, Wrapped::_type_tag on all objects are 0 and cast_to<T> always return nullptr.
The behavior depends on loading order of libraries. If I set one of the library autoload, then, it get access to cast_to<T> and others lost. If I autoload all library, only the first one get access to cast_to<T>.

## Tested environment
+ Godot Engine v3.2.stable.official 
+ godot-cpp : c2f765e49c7dd0c86729e6ba17f87c039203bce0
+ Ubuntu Linux
+ g++ (Ubuntu 9.3.0-10ubuntu1) 9.3.0

### gdn1.cpp

``` c++
// class GDN1 in libgdn1.so
#include <Godot.hpp>
#include <Node.hpp>
namespace godot
{
class GDN1 : public Node
{
  GODOT_CLASS(GDN1, Node)
public:
  static void _register_methods()
  {
    register_method("_process", &GDN1::_process);
  }
  void _init() {}
  void _process(float dt)
  {
    auto c = get_children();
    for (int i = 0; i < c.size(); ++i)
    {
      Godot::print(c[i]);
      Object *o = c[i];
      Godot::print("type tag: " + String::num_int64(o->_type_tag));
      Node *n = cast_to<Node>(c[i]);
      if (n)
      {
        Godot::print("cast_to<Node> success");
      }
    }
  }
};
} // namespace godot

extern "C" void GDN_EXPORT godot_gdnative_init(godot_gdnative_init_options *o)
{
  godot::Godot::gdnative_init(o);
}
extern "C" void GDN_EXPORT godot_gdnative_terminate(godot_gdnative_terminate_options *o)
{
  godot::Godot::gdnative_terminate(o);
}
extern "C" void GDN_EXPORT godot_nativescript_init(void *handle)
{
  godot::Godot::nativescript_init(handle);
  godot::register_class<godot::GDN1>();
}
```

### gdn1.gdnlib

``` ini
[general]

singleton=false
load_once=true
symbol_prefix="godot_"
reloadable=false

[entry]

X11.64="res://bin/x11/libgdn1.so"

[dependencies]

X11.64=[  ]
Windows.64=[  ]
OSX.64=[  ]
```

### gdn1.gdns

``` ini
[gd_resource type="NativeScript" load_steps=2 format=2]

[ext_resource path="res://bin/gdn1.gdnlib" type="GDNativeLibrary" id=1]

[resource]

resource_name = "gdn1"
class_name = "GDN1"
library = ExtResource( 1 )
_sections_unfolded = [ "Resource" ]
```

### code for class GDN2 and GDN2

I have class GDN2, GDN3 as well. These classes are almost identical as class GDN1. Only difference is their name.

### test.tscn

``` ini
[gd_scene load_steps=4 format=2]

[ext_resource path="res://bin/gdn1.gdns" type="Script" id=1]
[ext_resource path="res://bin/gdn2.gdns" type="Script" id=2]
[ext_resource path="res://bin/gdn3.gdns" type="Script" id=3]

[node name="Spatial" type="Spatial"]

[node name="Node" type="Node" parent="."]
script = ExtResource( 1 )

[node name="Node" type="Node" parent="Node"]

[node name="Node2" type="Node" parent="."]
script = ExtResource( 2 )

[node name="Node" type="Node" parent="Node2"]

[node name="Node3" type="Node" parent="."]
script = ExtResource( 3 )

[node name="Node" type="Node" parent="Node3"]
```

## Result
```
Godot Engine v3.2.stable.official - https://godotengine.org
OpenGL ES 3.0 Renderer: GeForce GTX 1080/PCIe/SSE2
 
[Node:1221]
type tag: -7978959854546214607
cast_to<Node> success
[Node:1223]
type tag: 0
[Node:1225]
type tag: 0
[Node:1221]
type tag: -7978959854546214607
cast_to<Node> success
[Node:1223]
type tag: 0
[Node:1225]
type tag: 0
```

## Expected result
```
[Node:1221]
type tag: -7978959854546214607
cast_to<Node> success
[Node:1223]
type tag: <<<non-zero integer>>>
cast_to<Node> success
[Node:1225]
type tag: <<<non-zero integer>>>
cast_to<Node> success
```

**Comment by m4gr3d** [comment] 2020-04-14 08:55
@BastiaanOlij Running into the same issue as well, which is pretty major because it limits the use of `godot-cpp` to a single library per project.

It seems the issue is caused by the init logic being static and global, as such each successive initialization overrides the one prior.
It could be resolved by having each library holds its own 'Godot state' object which would contain its initialization parameters and use that state when accessing Godot functionality.

**Comment by m4gr3d** [comment] 2020-04-14 19:27
Seems the issue is caused by the fact that [`register_global_type`](https://github.com/GodotNativeTools/godot-cpp/blob/c2f765e49c7dd0c86729e6ba17f87c039203bce0/src/core/TagDB.cpp#L26) makes use of [`godot::_RegisterState::language_index`](https://github.com/GodotNativeTools/godot-cpp/blob/c2f765e49c7dd0c86729e6ba17f87c039203bce0/include/core/GodotGlobal.hpp#L47) but is invoked prior to that field being properly set.

So all library instances override each other by using `godot::_RegisterState::language_index` with a value of `0`.
Moving the initialization of that field prior to invoking `register_global_type` resolves the issue.

**Comment by yosagi** [comment] 2020-04-15 01:44
@m4gr3d Thanks for the fix. It resolved the issue on my environment!

**Comment by BastiaanOlij** [comment] 2020-04-15 10:53
I've had problems with things being done too soon as well, I think a few things got mixed up when godot-cpp was changed to do all the bind logic at the start instead of lazy binding as objects get constructed.

**Closed** 2020-04-17 04:31 UTC
